# Learn more about filters
# https://api-platform.com/docs/core/filters
services:
    slug.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { slug: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    country.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { country.slug: 'exact' } ]
        tags: [ 'api_platform.filter' ]
