# Learn more about filters
# https://api-platform.com/docs/core/filters
    services:
        'AppBundle\Doctrine\ORM\Extension\CurrentUserExtension':
            arguments:
                - '@security.token_storage'
                - '@security.authorization_checker'
            tags:
                - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
                - { name: api_platform.doctrine.orm.query_extension.item }

    slug.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { slug: 'exact' } ]
        tags: [ 'api_platform.filter' ]

    country.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { country.slug: 'exact' } ]
        tags: [ 'api_platform.filter' ]
